services:
  farmos-application:
    container_name: farmos-application
    image: webgrip/farmos-application:latest
    pull_policy: never
    build:
      context: .
      dockerfile: ops/docker/application/Dockerfile
#      target: production
    restart: always
    depends_on:
      farmos-application-postgres:
        condition: service_started
    ports:
      - "0.0.0.0:80:8080"
    environment:
      SUBDOMAIN: ${SUBDOMAIN:-farmos-application}
      DOMAIN_NAME: ${DOMAIN_NAME:-webgrip.test}
      XDEBUG_MODE: debug
    labels:
      - "traefik.enable=true"

      # -------------------------------
      # 1) Router for HTTP (port 80)
      # -------------------------------
      - "traefik.http.routers.farmos-application.entrypoints=web"
      - "traefik.http.routers.farmos-application.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      # This middleware redirects to HTTPS
      - "traefik.http.routers.farmos-application.middlewares=redirect-to-https"

      # Define the middleware that redirects HTTP -> HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # --------------------------------
      # 2) Router for HTTPS (port 443)
      # --------------------------------
      - "traefik.http.routers.farmos-application-secure.entrypoints=websecure"
      - "traefik.http.routers.farmos-application-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.farmos-application-secure.tls=true"

      # Configure certs (the main domain + wildcard SAN)
      - "traefik.http.routers.farmos-application-secure.tls.domains[0].main=${SUBDOMAIN}.${DOMAIN_NAME}"
      - "traefik.http.routers.farmos-application-secure.tls.domains[0].sans=*.${DOMAIN_NAME}"

      # Attach this router to the 'farmos-application' service
      - "traefik.http.routers.farmos-application-secure.service=farmos-application@docker"

      # --------------------------------
      # 3) Service definition for farmos-application
      # --------------------------------
      - "traefik.http.services.farmos-application.loadbalancer.server.scheme=http"
      - "traefik.http.services.farmos-application.loadbalancer.server.port=80"

    env_file:
      - .env
    volumes:
      - farmos-application-data:/data
      - './src:/opt/drupal'

  farmos-application-mkcert:
    container_name: farmos-application-mkcert
    image: webgrip/traefik-local-development-mkcert:latest
    pull_policy: always
    volumes:
      - ~/.config/mkcert:/root/.local/share/mkcert:ro
      - certificate-data:/certificate-data:rw
    entrypoint: [ "/app/entrypoint.sh", "${DOMAIN_NAME}", "${SUBDOMAIN}.${DOMAIN_NAME}" ]

  farmos-application-postgres:
    build:
      context: .
      dockerfile: ops/docker/postgres/Dockerfile
    container_name: farmos-application-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-farm}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-farm}
      - POSTGRES_DB=${POSTGRES_DB:-farm}
    volumes:
      - farmos-application-postgres-data:/var/lib/postgresql/data

volumes:
  farmos-application-data:
  farmos-application-postgres-data:
  certificate-data:
    external: true

networks:
  default:
    external: true
    name: webgrip
