namespace: n8n-application

_shared_config:
  hostname: &hostname application.staging.k8s.webgrip.nl
  url: &url https://application.staging.k8s.webgrip.nl

application:
  enabled: true
  image:
    repository: webgrip/application-application
    tag: latest
    pullPolicy: Always

  ingress:
    enabled: true
    className: ingress-traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-traefik
#      traefik.ingress.kubernetes.io/router.middlewares: "ingress-traefik-ryan-basic-auth@kubernetescrd"
    hosts:
      - host: *hostname
        paths:
          - "/"
    tls:
      - secretName: letsencrypt-application-application
        hosts:
          - *hostname

postgresql:
  architecture: standalone

  auth:
    username: application
    database: application_db
    existingSecret: application-application-secrets
    secretKeys:
      userPasswordKey: postgres-password

  metrics:
    enabled: true

  primary:
    service:
      type: ClusterIP
      ports:
        postgresql: 5432

